name: time
description: A simple app to interface with TSheets Time.
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  after_layout: ^1.2.0
  auto_size_text: ^3.0.0
  codable:
    path: ../../Core/codable
  collection: ^1.17.0
  convert: ^3.1.1
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^3.3.1
  flutter_web_auth_2: ^2.1.4
  grouped_list: ^5.1.2
  http: ^0.13.5
  intl: ^0.18.1
  json_annotation: ^4.8.0
  modal_bottom_sheet: ^3.0.0-pre
  provider: ^6.0.5
  shared_preferences: ^2.1.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21